server:
  port: 10014
spring:
  profiles:
    active: prod
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erabbit_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: service-web-oauth
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true


feign:
  httpclient:
    enabled: true
    max-connections: 20
    max-connections-per-route: 30   # 连接池数量
#    connection-timeout: 10000
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
  hystrix:
    enabled: true
##ribbon:
##  ReadTimeout: 5000
##  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
##          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 12000
  threadpool:
    default:
#      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: 50                    #核心线程数
      maxQueueSize: 100               #最大队列数
      queueSizeRejectionThreshold: 100   #队列拒绝阈值设置


auth:
  clientId: erabbit
  clientSecret: erabbit
  location-file: erabbit.jks
#  cookieDomain: 192.168.0.97
#  cookieMaxAge: 7200

#证书和密钥配置
encrypt:
  key-store:
    #证书路径
    location: classpath:/erabbit.jks
    #密钥-别名-证书密码
    secret: erabbit
    alias: erabbit
    password: erabbit